# Generated by Django 5.2.4 on 2025-08-05 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcg_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcg_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('card_count', models.PositiveIntegerField(blank=True, null=True)),
                ('logo', models.URLField(blank=True)),
                ('symbol', models.URLField(blank=True)),
                ('boosters', models.ManyToManyField(blank=True, related_name='sets', to='tcg_collections.booster')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('tcg_id', models.CharField(max_length=50, unique=True)),
                ('illustrator', models.CharField(blank=True, max_length=100)),
                ('image_base', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=50)),
                ('types', models.JSONField(blank=True, default=list)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('hp', models.PositiveIntegerField(blank=True, null=True)),
                ('suffix', models.CharField(blank=True, max_length=50)),
                ('trainer_type', models.CharField(blank=True, max_length=50)),
                ('boosters', models.ManyToManyField(blank=True, related_name='cards', to='tcg_collections.booster')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tcg_collections.set')),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('for_trade', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcg_collections.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'card')},
            },
        ),
    ]
