# Generated by Django 5.2.5 on 2025-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packpickerdata',
            name='last_refresh',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last sim run', null=True),
        ),
    ]
