# Generated by Django 5.2.4 on 2025-08-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='release_date',
        ),
    ]
