# Generated by Django 5.2.4 on 2025-08-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0002_remove_set_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='card_count',
            new_name='card_count_official',
        ),
        migrations.AddField(
            model_name='set',
            name='card_count_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
