# Generated by Django 5.2.5 on 2025-09-22 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0002_alter_packpickerdata_last_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packpickerdata',
            name='last_refresh',
            field=models.DateTimeField(default=datetime.date(2025, 1, 1), help_text='Timestamp of last sim run'),
        ),
    ]
