# Generated by Django 5.2.4 on 2025-08-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0003_rename_card_count_set_card_count_official_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
