# Generated by Django 5.2.4 on 2025-08-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0004_set_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_tradeable',
            field=models.BooleanField(default=False),
        ),
    ]
