# Generated by Django 5.2.5 on 2025-09-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0004_alter_usercollection_user_alter_userwant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='local_image_small',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
