# Generated by Django 5.2.5 on 2025-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0005_alter_card_local_image_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='set',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='set_logos/'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='local_image_small',
            field=models.ImageField(blank=True, null=True, upload_to='boosters/'),
        ),
    ]
