# Generated by Django 5.2.5 on 2025-09-24 01:24

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0006_remove_set_logo_path_set_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='set_logos/'),
        ),
    ]
