# Generated by Django 5.2.4 on 2025-08-06 20:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWants',
            new_name='UserWant',
        ),
    ]
