# Generated by Django 5.2.5 on 2025-09-24 17:57

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0007_alter_set_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='local_image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage, upload_to='media/boosters/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='local_image_small',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='media/cards/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=True, help_text='Enable dark mode theme'),
        ),
        migrations.AlterField(
            model_name='set',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='media/set_logos/'),
        ),
    ]
