# Generated by Django 5.2.5 on 2025-09-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0008_alter_booster_local_image_small_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
