# Generated by Django 5.2.4 on 2025-08-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0009_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterDropRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('1-3', 'Slots 1-3 (Always One Diamond)'), ('4', 'Slot 4 (Non-One Diamond, Weighted Low)'), ('5', 'Slot 5 (Non-One Diamond, Better Odds)'), ('god', 'God Pack (All One-Star+, Rare)'), ('6', '6th Card (5% Chance, Exclusives)')], max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('probability', models.FloatField(help_text='Probability (0.0 to 1.0)')),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcg_collections.booster')),
            ],
            options={
                'unique_together': {('booster', 'slot', 'rarity')},
            },
        ),
    ]
