# Generated by Django 5.2.4 on 2025-08-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0010_boosterdroprate'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='manual_boosters_added',
            field=models.BooleanField(default=False, help_text='Set to True if boosters were manually assigned'),
        ),
    ]
