# Generated by Django 5.2.4 on 2025-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0011_card_manual_boosters_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='god_pack_prob',
            field=models.FloatField(default=0.0, help_text='Base probability of god pack (e.g., 0.0005)'),
        ),
        migrations.AddField(
            model_name='booster',
            name='sixth_card_prob',
            field=models.FloatField(default=0.0, help_text='Base probability of 6th card (e.g., 0.05)'),
        ),
    ]
