# Generated by Django 5.2.4 on 2025-08-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0012_booster_god_pack_prob_booster_sixth_card_prob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='god_pack_prob',
            field=models.FloatField(default=0.0005, help_text='Base probability of god pack (e.g., 0.0005)'),
        ),
    ]
