# Generated by Django 5.2.4 on 2025-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0013_alter_booster_god_pack_prob'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='local_image_small',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
