# Generated by Django 5.2.4 on 2025-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0014_card_local_image_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='types',
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
