# Generated by Django 5.2.4 on 2025-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0015_remove_card_types_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='local_image_large',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
