# Generated by Django 5.2.4 on 2025-08-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0016_card_local_image_large'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='local_image_large',
        ),
    ]
