# Generated by Django 5.2.4 on 2025-08-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0017_remove_card_local_image_large'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='logo',
        ),
        migrations.AddField(
            model_name='set',
            name='logo_path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
