# Generated by Django 5.2.5 on 2025-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0018_remove_set_logo_set_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
