# Generated by Django 5.2.5 on 2025-08-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0019_usercollection_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='local_image_small',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
