# Generated by Django 5.2.5 on 2025-08-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0020_booster_local_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='local_image_small',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
