# Generated by Django 5.2.5 on 2025-08-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0021_alter_booster_local_image_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_set',
            field=models.ForeignKey(blank=True, help_text='Your favorite TCG Pocket set.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcg_collections.set'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
