# Generated by Django 5.2.5 on 2025-08-16 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0022_profile_favorite_set_profile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share_token',
            field=models.UUIDField(null=True),
        ),
    ]
