# Generated by Django 5.2.5 on 2025-08-16 16:59

from django.db import migrations
import uuid

def set_share_tokens(apps, schema_editor):
    Profile = apps.get_model('tcg_collections', 'Profile')
    for profile in Profile.objects.filter(share_token__isnull=True):
        profile.share_token = uuid.uuid4()
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0023_profile_share_token'),
    ]

    operations = [
        migrations.RunPython(set_share_tokens),
    ]
