# Generated by Django 5.2.5 on 2025-08-16 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0024_auto_20250816_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
