# Generated by Django 5.2.5 on 2025-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0025_alter_profile_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_favorites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
