# Generated by Django 5.2.5 on 2025-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0027_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('collection_add', 'Collection Add'), ('pack_open', 'Pack Open')], max_length=50),
        ),
    ]
