# Generated by Django 5.2.5 on 2025-08-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0028_profile_pic_config_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic_config',
            field=models.JSONField(default=dict),
        ),
    ]
