# Generated by Django 5.2.5 on 2025-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0029_alter_profile_pic_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
