# Generated by Django 5.2.5 on 2025-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0031_alter_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode theme'),
        ),
    ]
