# Generated by Django 5.2.5 on 2025-08-23 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0033_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='offered_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_matches', to='tcg_collections.card'),
        ),
        migrations.AddField(
            model_name='match',
            name='received_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_in_matches', to='tcg_collections.card'),
        ),
    ]
