# Generated by Django 5.2.5 on 2025-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0034_match_offered_card_match_received_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='for_trade',
        ),
        migrations.AddField(
            model_name='profile',
            name='trade_threshold',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Trade down to 1'), (2, 'Keep 2 for decks')], default=2),
        ),
    ]
