# Generated by Django 5.2.5 on 2025-08-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0035_remove_usercollection_for_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepted_trades_this_month',
            field=models.PositiveIntegerField(default=0, help_text='Count of accepted trades in current month.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium subscriber status.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_trade_month',
            field=models.DateField(blank=True, help_text='Last month trades were reset.', null=True),
        ),
    ]
