# Generated by Django 5.2.5 on 2025-09-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0036_profile_accepted_trades_this_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='is_favorite',
        ),
    ]
