# Generated by Django 5.2.5 on 2025-09-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0037_remove_usercollection_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_favorites',
        ),
    ]
