# Generated by Django 5.2.5 on 2025-09-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0038_remove_profile_display_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_set',
        ),
    ]
