# Generated by Django 5.2.5 on 2025-09-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0039_remove_profile_favorite_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_sixth_exclusive',
            field=models.BooleanField(default=False, help_text='True if this card is exclusive to the 6th slot in packs'),
        ),
    ]
