# Generated by Django 5.2.5 on 2025-09-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0040_card_is_sixth_exclusive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refresh', models.DateTimeField(blank=True, help_text='Timestamp of last sim run', null=True)),
                ('refresh_count', models.PositiveIntegerField(default=0, help_text='Count for current period (e.g., reset daily/hourly)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackPickerBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_new', models.FloatField(default=0.0)),
                ('expected_new', models.FloatField(default=0.0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcg_collections.booster')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosters', to='tcg_collections.packpickerdata')),
            ],
            options={
                'ordering': ['-chance_new'],
                'unique_together': {('data', 'booster')},
            },
        ),
        migrations.CreateModel(
            name='PackPickerRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=50)),
                ('chance_new', models.FloatField(default=0.0)),
                ('expected_new', models.FloatField(default=0.0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rarities', to='tcg_collections.packpickerbooster')),
            ],
            options={
                'unique_together': {('booster', 'rarity')},
            },
        ),
    ]
