# Generated by Django 5.2.5 on 2025-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0041_packpickerdata_packpickerbooster_packpickerrarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packpickerbooster',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packpickerrarity',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
