# Generated by Django 5.2.5 on 2025-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0042_packpickerbooster_total_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packpickerbooster',
            name='base_chance_new',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packpickerbooster',
            name='base_missing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packpickerbooster',
            name='base_total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packpickerbooster',
            name='rare_chance_new',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packpickerbooster',
            name='rare_missing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packpickerbooster',
            name='rare_total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
