# Generated by Django 5.2.5 on 2025-09-18 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0043_packpickerbooster_base_chance_new_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'timestamp'], name='tcg_collect_user_id_33e476_idx'),
        ),
        migrations.AddIndex(
            model_name='packpickerbooster',
            index=models.Index(fields=['data', 'chance_new'], name='tcg_collect_data_id_31418a_idx'),
        ),
        migrations.AddIndex(
            model_name='packpickerrarity',
            index=models.Index(fields=['booster', 'rarity'], name='tcg_collect_booster_31028c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['user', 'quantity'], name='tcg_collect_user_id_bbdfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='usercollection',
            index=models.Index(fields=['user', 'card'], name='tcg_collect_user_id_40c0d1_idx'),
        ),
    ]
