# Generated by Django 5.2.5 on 2025-09-21 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0044_activity_tcg_collect_user_id_33e476_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('packs_opened', models.PositiveIntegerField(default=0)),
                ('rare_cards_found', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_cards_added', models.PositiveIntegerField(default=0)),
                ('four_diamond_found', models.PositiveIntegerField(default=0)),
                ('one_star_found', models.PositiveIntegerField(default=0)),
                ('two_star_found', models.PositiveIntegerField(default=0)),
                ('three_star_found', models.PositiveIntegerField(default=0)),
                ('one_shiny_found', models.PositiveIntegerField(default=0)),
                ('two_shiny_found', models.PositiveIntegerField(default=0)),
                ('crown_found', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
