# Generated by Django 5.2.5 on 2025-09-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0045_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='DailyStat',
        ),
    ]
