# Generated by Django 5.2.5 on 2025-09-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0046_rename_stats_dailystat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystat',
            name='total_cards_added',
        ),
    ]
