# Generated by Django 5.2.5 on 2025-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0047_remove_dailystat_total_cards_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
