# Generated by Django 5.2.5 on 2025-09-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0048_dailystat_active_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystat',
            name='active_users',
        ),
    ]
