# Generated by Django 5.2.5 on 2025-09-22 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcg_collections', '0049_remove_dailystat_active_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packpickerdata',
            name='last_refresh',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 6, 35, 27, 589188, tzinfo=datetime.timezone.utc), help_text='Timestamp of last sim run'),
        ),
        migrations.AlterField(
            model_name='packpickerdata',
            name='refresh_count',
            field=models.PositiveIntegerField(default=1, help_text='Count for current period (e.g., reset daily/hourly)'),
        ),
    ]
